# Mods to load on all connections.
mods = ["best_bot", "rss", "policing"]

[connections]

  [connections.libera]
  type = "irc"
  admins = ["nick@user/nick"]
  server = "irc.libera.chat:6667"
  nick = "Guest1"

  [connections.discord]
  type = "discord"
  admins = ["1234"]
  mods = ["meme_police"]
  token = "$DISCORD_TOKEN"
